[package]
name = "nrf51"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
cortexm0 = { path = "../../arch/cortex-m0" }
tock_rt0 = { path = "../../libraries/tock-rt0" }
kernel = { path = "../../kernel" }

[dependencies.nrf5x]
path = "../nrf5x"
features = ["nrf51"]
